// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mecpl-about-sectors/Current.tsx": () => import("../components/mockups/mecpl-about-sectors/Current.tsx"),
  "./components/mockups/mecpl-about-sectors/Reference.tsx": () => import("../components/mockups/mecpl-about-sectors/Reference.tsx"),
  "./components/mockups/mecpl-founder/Current.tsx": () => import("../components/mockups/mecpl-founder/Current.tsx"),
  "./components/mockups/mecpl-founder/Reference.tsx": () => import("../components/mockups/mecpl-founder/Reference.tsx"),
  "./components/mockups/mecpl-journey/Current.tsx": () => import("../components/mockups/mecpl-journey/Current.tsx"),
  "./components/mockups/mecpl-journey/Reference.tsx": () => import("../components/mockups/mecpl-journey/Reference.tsx"),
  "./components/mockups/mecpl-people-safety/Current.tsx": () => import("../components/mockups/mecpl-people-safety/Current.tsx"),
  "./components/mockups/mecpl-purpose/Current.tsx": () => import("../components/mockups/mecpl-purpose/Current.tsx"),
  "./components/mockups/mecpl-purpose/Reference.tsx": () => import("../components/mockups/mecpl-purpose/Reference.tsx"),
  "./components/mockups/mecpl-stats-transition/AppliedStats.tsx": () => import("../components/mockups/mecpl-stats-transition/AppliedStats.tsx"),
  "./components/mockups/mecpl-stats-transition/Current.tsx": () => import("../components/mockups/mecpl-stats-transition/Current.tsx"),
  "./components/mockups/mecpl-stats-transition/OpenEditorial.tsx": () => import("../components/mockups/mecpl-stats-transition/OpenEditorial.tsx"),
  "./components/mockups/mecpl-stats-transition/SeamlessLightBand.tsx": () => import("../components/mockups/mecpl-stats-transition/SeamlessLightBand.tsx"),
  "./components/mockups/mecpl-stats-transition/UnifiedCharcoalBand.tsx": () => import("../components/mockups/mecpl-stats-transition/UnifiedCharcoalBand.tsx")
};
